import React, { useState, useRef, useEffect } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import HomeBody from '../src/components/HomePage/HomeBody';
import Login from './login';
import { createPortal } from 'react-dom';
import { noop } from 'lodash';


export default function Home() {
  const [isHomeModalOpen, setIsHomeModalOpen] = useState(true);
  const ref = useRef();
  const mainRoot = useRef(null);

  const [isMouseDown, setIsMouseDown] = useState(false);

  const [mousePosition, setMousePosition] = useState({ screenHeight: 1000, startPosition: { x: 1000, y: 1000 }, currentPosition: { x: 1000, y: 1000 } });
  
  const onMouseDown = (event) => {
    setIsMouseDown(true);
    const domRect = ref.current.getBoundingClientRect();
    let x = event.clientX - domRect.left;
    let y = event.clientY - domRect.top;
    setMousePosition((prevState) => ({ ...prevState, screenHeight: domRect.height, startPosition: { x, y }, currentPosition: { x: domRect.height, y: domRect.height } }));
    // console.log(domRect);x
    // console.log("start position", mousePosition);
  };

  const onMouseMove = (event) => {
    const domRect = ref.current.getBoundingClientRect();
    const maxScroll = (mousePosition.startPosition.y < domRect.height * 0.3) ? (mousePosition.startPosition.y - (mousePosition.startPosition.y * 0.05)) : (domRect.height * 0.3);
    if (isMouseDown) {
      // let x = event.clientX - domRect.left;
      // let y = event.clientY - domRect.top;
      // console.log(event.clientY);
      // console.log(x, y);
      setMousePosition((prevState) => ({ ...prevState, currentPosition: { x: event.clientX, y: event.clientY } }));
    } else noop;
    // console.log("maxScroll", maxScroll); 
    // console.log("domRect.height", domRect.height); 
    // console.log("mousePosition.startPosition.y", mousePosition.startPosition.y); 
  };

  console.log(mousePosition.screenHeight);
  console.log(mousePosition.currentPosition.y);
  console.log(mousePosition.screenHeight - mousePosition.currentPosition.y);

  return (
    <><Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
      <div style={{ width: '100%', height: '100%'  }} ref={mainRoot}>
        <Login/>
        <div className='modal' 
          ref={ref} 
          style={{ bottom: !isMouseDown ? 0 : `${(mousePosition.screenHeight - mousePosition.currentPosition.y) - (mousePosition.screenHeight - mousePosition.startPosition.y)}px` }}
          onMouseDown={(event) => onMouseDown(event)} 
          onMouseUp={() => {
            setIsMouseDown(false);
            console.log(1);
          }} 
          onMouseMove={(event) => onMouseMove(event)}
        >
          <HomeBody />
        </div>
      </div>
    </>
    
    )
  }

  // const HomePageModal = ({ children }) => {
  //   const domElement = document.getElementById('__next');
  //   const domElement = mainRoot.current;
  //   return createPortal(children, domElement);
  // };
  
  {/* <HomePageModal> */}
    {/* <HomeBody ref={ref}/> */}
  {/* </HomePageModal> */}

{/* <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div> */}